name: CI

on: [push, pull_request]

jobs:
  appimage-x86_64:
    name: Ubuntu latest x86_64 AppImage build
    runs-on: ubuntu-latest
    env:
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmagic-dev libjpeg-dev libpng-dev cimg-dev
      - name: Build AppImage
        run: bash -ex ci/build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage x86_64
          path: linuxdeploy*.AppImage*

  appimage-i386:
    name: Ubuntu latest i386 AppImage build
    runs-on: ubuntu-latest
    env:
      ARCH: i386
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libmagic-dev:i386 libjpeg-dev:i386 libpng-dev:i386 cimg-dev gcc-multilib g++-multilib libfuse2:i386
      - name: Build AppImage
        run: bash -ex ci/build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage i386
          path: linuxdeploy*.AppImage*

  coverage-x86_64:
    name: Ubuntu latest x86_64 coverage build (no binaries uploaded)
    runs-on: ubuntu-latest
    env:
      ARCH: x86_64
      BUILD_TYPE: coverage
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmagic-dev libjpeg-dev libpng-dev cimg-dev
      - name: Build AppImage
        run: bash -ex ci/build.sh

  coverage-i386:
    name: Ubuntu latest x86_64 coverage build (no binaries uploaded)
    runs-on: ubuntu-latest
    env:
      ARCH: x86_64
      BUILD_TYPE: coverage
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmagic-dev libjpeg-dev libpng-dev cimg-dev
      - name: Build AppImage
        run: bash -ex ci/build.sh

  upload:
    name: Create release and upload artifacts
    needs:
      - appimage-x86_64
      - appimage-i386
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/linuxdeploy*.AppImage*
